// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1) {
  return window['go']['main']['App']['ApplyChanges'](arg1);
}

export function LoadJSON() {
  return window['go']['main']['App']['LoadJSON']();
}

export function SaveChanges(arg1) {
  return window['go']['main']['App']['SaveChanges'](arg1);
}

export function ScanDirectory() {
  return window['go']['main']['App']['ScanDirectory']();
}
