// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyChanges(arg1:string):Promise<void>;

export function LoadJSON():Promise<string>;

export function SaveChanges(arg1:string):Promise<void>;

export function ScanDirectory():Promise<Array<main.FileInfo>>;
